services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    mem_limit: 2g  # ✅ dit werkt wél met gewone `docker compose up`
