services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped

    # Voeg een memorylimiet toe voor runtime (nodig op sommige Docker setups)
    deploy:
      resources:
        limits:
          memory: 2g
